version: "3"

networks:
  default:
    driver: bridge

services:

  node:
    image: node:10
    volumes:
      - ./:/var/www:cached
    ports:
      - "3000:3000"
    working_dir: /var/www
    command: sh -c "yarn install && yarn run start"
    networks:
      - default